name: Stage the app

on:
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: breaman-azure-ttt
  IMAGE_REPOSITORY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: breaman-ttt-app

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')